# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f2f5d4cc19080530ceec207ba5b85adfa0450eda27e34d45a56797d939116e8334829a80e8b4d3cbb0fe60446caeaa0eaa9706d0050ad4977d0ab5f7e3c9f05

test:
  secret_key_base: 0eed3afef31d6f72417b48175f1bae7be2651bdb38c4d46136c3a8dfb8d935371da2882d7db64e6c1254b5b88b3ce6c1cf51f4b881372f860633d1ed9200995f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
